Repository CleanroomMC/BetterQuesting, pull requests merged in 2022-07, with the labels that each got.

#51 Add GitHub Workflows for CI Mod Releases
  .github/release.yml
  .github/workflows/curseforge_release.yml
  .github/workflows/github_release.yml
Labels: enhancement

#50 Fix server crash with questbook
  src/main/java/betterquesting/handlers/GuiHandler.java
  src/main/java/betterquesting/items/ItemQuestBook.java
Labels: bugfix

#52 Further CI Work
  .github/release.yml
  .github/workflows/curseforge_release.yml
  .github/workflows/enforce_pr_labels.yml
Labels: enhancement, skip-changelog

#54 Update mod information
  gradle.properties
  src/main/java/betterquesting/core/BetterQuesting.java
  src/main/resources/mcmod.info
  src/main/resources/pack.mcmeta
Labels: enhancement

#55 cancel previous runs on pr label workflow
  .github/workflows/enforce_pr_labels.yml
Labels: skip-changelog

#53 Fail GitHub release when Tags Clash
  .github/workflows/github_release.yml
Labels: skip-changelog
